version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  eslint:
    executor:
      name: node/default
      tag: '10.17'
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
      - run: npm run build && ls dist
  example:
    executor:
      name: node/default
      tag: '10.17'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          working_directory: ~/repo/example
          name: Install
          command: npm install
      - run:
          working_directory: ~/repo/example
          name: Build
          command: npm run build && ls dist

workflows:
  ci:
    jobs:
      - eslint
      - example
