name: ESLint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run lint
      - run: npm run build && ls dist
