name: Example
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        working-directory: example
        run: npm install && npm install --save @mpan-wework/react-store@latest
      - name: Build
        working-directory: example
        run: npm run build && ls dist
